// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userGrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResInfo struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResInfo) Reset()         { *m = ResInfo{} }
func (m *ResInfo) String() string { return proto.CompactTextString(m) }
func (*ResInfo) ProtoMessage()    {}
func (*ResInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *ResInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResInfo.Unmarshal(m, b)
}
func (m *ResInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResInfo.Marshal(b, m, deterministic)
}
func (m *ResInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResInfo.Merge(m, src)
}
func (m *ResInfo) XXX_Size() int {
	return xxx_messageInfo_ResInfo.Size(m)
}
func (m *ResInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResInfo proto.InternalMessageInfo

func (m *ResInfo) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  int64                `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	NickName             string               `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Telephone            string               `protobuf:"bytes,5,opt,name=Telephone,proto3" json:"Telephone,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	ProfileImages        string               `protobuf:"bytes,7,opt,name=ProfileImages,proto3" json:"ProfileImages,omitempty"`
	FollowsCount         int64                `protobuf:"varint,8,opt,name=FollowsCount,proto3" json:"FollowsCount,omitempty"`
	FriendsCount         int64                `protobuf:"varint,9,opt,name=FriendsCount,proto3" json:"FriendsCount,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetProfileImages() string {
	if m != nil {
		return m.ProfileImages
	}
	return ""
}

func (m *User) GetFollowsCount() int64 {
	if m != nil {
		return m.FollowsCount
	}
	return 0
}

func (m *User) GetFriendsCount() int64 {
	if m != nil {
		return m.FriendsCount
	}
	return 0
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type MultiUsers struct {
	UserInfo             []*User  `protobuf:"bytes,1,rep,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiUsers) Reset()         { *m = MultiUsers{} }
func (m *MultiUsers) String() string { return proto.CompactTextString(m) }
func (*MultiUsers) ProtoMessage()    {}
func (*MultiUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *MultiUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiUsers.Unmarshal(m, b)
}
func (m *MultiUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiUsers.Marshal(b, m, deterministic)
}
func (m *MultiUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiUsers.Merge(m, src)
}
func (m *MultiUsers) XXX_Size() int {
	return xxx_messageInfo_MultiUsers.Size(m)
}
func (m *MultiUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiUsers.DiscardUnknown(m)
}

var xxx_messageInfo_MultiUsers proto.InternalMessageInfo

func (m *MultiUsers) GetUserInfo() []*User {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type Uid struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uid) Reset()         { *m = Uid{} }
func (m *Uid) String() string { return proto.CompactTextString(m) }
func (*Uid) ProtoMessage()    {}
func (*Uid) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Uid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uid.Unmarshal(m, b)
}
func (m *Uid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uid.Marshal(b, m, deterministic)
}
func (m *Uid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uid.Merge(m, src)
}
func (m *Uid) XXX_Size() int {
	return xxx_messageInfo_Uid.Size(m)
}
func (m *Uid) XXX_DiscardUnknown() {
	xxx_messageInfo_Uid.DiscardUnknown(m)
}

var xxx_messageInfo_Uid proto.InternalMessageInfo

func (m *Uid) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type Uids struct {
	SingleUid            []*Uid   `protobuf:"bytes,1,rep,name=singleUid,proto3" json:"singleUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uids) Reset()         { *m = Uids{} }
func (m *Uids) String() string { return proto.CompactTextString(m) }
func (*Uids) ProtoMessage()    {}
func (*Uids) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *Uids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uids.Unmarshal(m, b)
}
func (m *Uids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uids.Marshal(b, m, deterministic)
}
func (m *Uids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uids.Merge(m, src)
}
func (m *Uids) XXX_Size() int {
	return xxx_messageInfo_Uids.Size(m)
}
func (m *Uids) XXX_DiscardUnknown() {
	xxx_messageInfo_Uids.DiscardUnknown(m)
}

var xxx_messageInfo_Uids proto.InternalMessageInfo

func (m *Uids) GetSingleUid() []*Uid {
	if m != nil {
		return m.SingleUid
	}
	return nil
}

type UserRes struct {
	Res                  *ResInfo `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Info                 *User    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRes) Reset()         { *m = UserRes{} }
func (m *UserRes) String() string { return proto.CompactTextString(m) }
func (*UserRes) ProtoMessage()    {}
func (*UserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRes.Unmarshal(m, b)
}
func (m *UserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRes.Marshal(b, m, deterministic)
}
func (m *UserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRes.Merge(m, src)
}
func (m *UserRes) XXX_Size() int {
	return xxx_messageInfo_UserRes.Size(m)
}
func (m *UserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UserRes proto.InternalMessageInfo

func (m *UserRes) GetRes() *ResInfo {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *UserRes) GetInfo() *User {
	if m != nil {
		return m.Info
	}
	return nil
}

type MultiUsersRes struct {
	Res                  *ResInfo    `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Info                 *MultiUsers `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MultiUsersRes) Reset()         { *m = MultiUsersRes{} }
func (m *MultiUsersRes) String() string { return proto.CompactTextString(m) }
func (*MultiUsersRes) ProtoMessage()    {}
func (*MultiUsersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *MultiUsersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiUsersRes.Unmarshal(m, b)
}
func (m *MultiUsersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiUsersRes.Marshal(b, m, deterministic)
}
func (m *MultiUsersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiUsersRes.Merge(m, src)
}
func (m *MultiUsersRes) XXX_Size() int {
	return xxx_messageInfo_MultiUsersRes.Size(m)
}
func (m *MultiUsersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiUsersRes.DiscardUnknown(m)
}

var xxx_messageInfo_MultiUsersRes proto.InternalMessageInfo

func (m *MultiUsersRes) GetRes() *ResInfo {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *MultiUsersRes) GetInfo() *MultiUsers {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*ResInfo)(nil), "userGrpc.ResInfo")
	proto.RegisterType((*User)(nil), "userGrpc.User")
	proto.RegisterType((*MultiUsers)(nil), "userGrpc.MultiUsers")
	proto.RegisterType((*Uid)(nil), "userGrpc.Uid")
	proto.RegisterType((*Uids)(nil), "userGrpc.Uids")
	proto.RegisterType((*UserRes)(nil), "userGrpc.UserRes")
	proto.RegisterType((*MultiUsersRes)(nil), "userGrpc.MultiUsersRes")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0x36, 0xfd, 0xdd, 0xa9, 0x2d, 0xde, 0x72, 0x70, 0x4b, 0x10, 0x2c, 0xab, 0x0f, 0x41, 0x31,
	0x85, 0xde, 0x8b, 0xe8, 0x83, 0xe8, 0xa1, 0xa5, 0x0f, 0x77, 0x1c, 0xa1, 0x7d, 0x15, 0xd2, 0xee,
	0x34, 0x2e, 0x26, 0xd9, 0x90, 0x4d, 0x39, 0xfc, 0x8f, 0xfd, 0x1b, 0x7c, 0x92, 0x9d, 0x34, 0x4d,
	0x53, 0x0e, 0xbc, 0xb7, 0xd9, 0xf9, 0xbe, 0xf9, 0x76, 0x66, 0xbe, 0x01, 0xd8, 0x1b, 0xcc, 0xfd,
	0x2c, 0xd7, 0x85, 0x66, 0x03, 0x1b, 0x2f, 0xf2, 0x6c, 0xeb, 0xbe, 0x8a, 0xb4, 0x8e, 0x62, 0x9c,
	0x51, 0x7e, 0xb3, 0xdf, 0xcd, 0x0a, 0x95, 0xa0, 0x29, 0xc2, 0x24, 0x2b, 0xa9, 0x62, 0x06, 0xfd,
	0x00, 0xcd, 0x32, 0xdd, 0x69, 0xc6, 0xa0, 0xb3, 0xd5, 0x12, 0xb9, 0x33, 0x75, 0xbc, 0x6e, 0x40,
	0x31, 0x7b, 0x01, 0xed, 0xc4, 0x44, 0xbc, 0x35, 0x75, 0xbc, 0x61, 0x60, 0x43, 0xf1, 0xb7, 0x05,
	0x9d, 0xb5, 0xc1, 0x9c, 0x4d, 0xa0, 0xb5, 0x94, 0x07, 0x72, 0x6b, 0x29, 0x2d, 0x75, 0xad, 0x24,
	0x51, 0xdb, 0x81, 0x0d, 0x99, 0x0b, 0x83, 0x3b, 0xb5, 0xfd, 0x75, 0x17, 0x26, 0xc8, 0xdb, 0xa4,
	0x70, 0x7c, 0x5b, 0xec, 0x3e, 0x34, 0xe6, 0x41, 0xe7, 0x92, 0x77, 0x4a, 0xac, 0x7a, 0xb3, 0x97,
	0x30, 0x5c, 0x61, 0x8c, 0xd9, 0x4f, 0x9d, 0x22, 0xef, 0x12, 0x58, 0x27, 0xd8, 0x25, 0x74, 0xbf,
	0x25, 0xa1, 0x8a, 0x79, 0x8f, 0x90, 0xf2, 0xc1, 0xde, 0xc0, 0xf8, 0x3e, 0xd7, 0x3b, 0x15, 0xe3,
	0x32, 0x09, 0x23, 0x34, 0xbc, 0x4f, 0x68, 0x33, 0xc9, 0x04, 0x3c, 0xff, 0xae, 0xe3, 0x58, 0x3f,
	0x98, 0x1b, 0xbd, 0x4f, 0x0b, 0x3e, 0xa0, 0x66, 0x1b, 0x39, 0xe2, 0xe4, 0x0a, 0x53, 0x79, 0xe0,
	0x0c, 0x0f, 0x9c, 0x93, 0x1c, 0xfb, 0x08, 0x70, 0x93, 0x63, 0x58, 0xe0, 0x4a, 0x25, 0xc8, 0x61,
	0xea, 0x78, 0xa3, 0xb9, 0xeb, 0x97, 0xbb, 0xf6, 0xab, 0x5d, 0xfb, 0xab, 0x6a, 0xd7, 0xc1, 0x09,
	0xdb, 0xd6, 0xae, 0x33, 0x59, 0xd5, 0x8e, 0xfe, 0x5f, 0x5b, 0xb3, 0xc5, 0x07, 0x80, 0xdb, 0x7d,
	0x5c, 0x28, 0x6b, 0x80, 0x61, 0x6f, 0x61, 0x60, 0x03, 0x6b, 0x1e, 0x77, 0xa6, 0x6d, 0x6f, 0x34,
	0x9f, 0xf8, 0x95, 0xf3, 0xbe, 0x45, 0x82, 0x23, 0x2e, 0xae, 0xc8, 0x9d, 0xca, 0x24, 0xe7, 0x68,
	0x92, 0xb8, 0x86, 0xce, 0x5a, 0x49, 0xc3, 0xde, 0xc1, 0xd0, 0xa8, 0x34, 0x8a, 0xb1, 0xc4, 0xad,
	0xda, 0xf8, 0x44, 0x4d, 0xc9, 0xa0, 0xc6, 0x45, 0x00, 0x7d, 0xd2, 0x47, 0xc3, 0x5e, 0x43, 0x3b,
	0x47, 0x43, 0x8a, 0xa3, 0xf9, 0x45, 0x5d, 0x71, 0xb8, 0xaa, 0xc0, 0xa2, 0x4c, 0x40, 0x47, 0xd9,
	0x2e, 0x5b, 0xc4, 0x3a, 0xef, 0x92, 0x30, 0xf1, 0x03, 0xc6, 0xf5, 0x6c, 0x4f, 0x56, 0xf6, 0x1a,
	0xca, 0x97, 0x35, 0xeb, 0x44, 0x8b, 0x18, 0xf3, 0x3f, 0x0e, 0x0c, 0x6f, 0x37, 0xb1, 0x8e, 0xe8,
	0x7a, 0xdf, 0x43, 0xaf, 0xf4, 0x84, 0x9d, 0x75, 0xe3, 0x5e, 0x9c, 0x75, 0x87, 0x46, 0x3c, 0x63,
	0x3e, 0x0c, 0x16, 0x58, 0x7c, 0xfd, 0x6d, 0x77, 0xd8, 0x5c, 0xcb, 0xe3, 0xfc, 0xcf, 0xc0, 0x89,
	0x6f, 0xef, 0x3d, 0x0d, 0x13, 0xfc, 0x92, 0xca, 0xe3, 0x79, 0x3f, 0xe9, 0xc3, 0x4f, 0x30, 0x59,
	0x60, 0x41, 0x43, 0xd0, 0xaf, 0xa6, 0x51, 0xa6, 0xa4, 0x71, 0xaf, 0x1e, 0x9d, 0xd5, 0x16, 0x6f,
	0x7a, 0x74, 0x46, 0xd7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x62, 0xa6, 0x72, 0xd2, 0x14, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MblogUserClient is the client API for MblogUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MblogUserClient interface {
	Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserRes, error)
	GetByUid(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*UserRes, error)
	GetByNicknameAndPassword(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserRes, error)
	GetMultiByUids(ctx context.Context, in *Uids, opts ...grpc.CallOption) (*MultiUsersRes, error)
}

type mblogUserClient struct {
	cc *grpc.ClientConn
}

func NewMblogUserClient(cc *grpc.ClientConn) MblogUserClient {
	return &mblogUserClient{cc}
}

func (c *mblogUserClient) Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserRes, error) {
	out := new(UserRes)
	err := c.cc.Invoke(ctx, "/userGrpc.MblogUser/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mblogUserClient) GetByUid(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*UserRes, error) {
	out := new(UserRes)
	err := c.cc.Invoke(ctx, "/userGrpc.MblogUser/GetByUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mblogUserClient) GetByNicknameAndPassword(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserRes, error) {
	out := new(UserRes)
	err := c.cc.Invoke(ctx, "/userGrpc.MblogUser/GetByNicknameAndPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mblogUserClient) GetMultiByUids(ctx context.Context, in *Uids, opts ...grpc.CallOption) (*MultiUsersRes, error) {
	out := new(MultiUsersRes)
	err := c.cc.Invoke(ctx, "/userGrpc.MblogUser/GetMultiByUids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MblogUserServer is the server API for MblogUser service.
type MblogUserServer interface {
	Create(context.Context, *User) (*UserRes, error)
	GetByUid(context.Context, *Uid) (*UserRes, error)
	GetByNicknameAndPassword(context.Context, *User) (*UserRes, error)
	GetMultiByUids(context.Context, *Uids) (*MultiUsersRes, error)
}

func RegisterMblogUserServer(s *grpc.Server, srv MblogUserServer) {
	s.RegisterService(&_MblogUser_serviceDesc, srv)
}

func _MblogUser_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MblogUserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userGrpc.MblogUser/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MblogUserServer).Create(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _MblogUser_GetByUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MblogUserServer).GetByUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userGrpc.MblogUser/GetByUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MblogUserServer).GetByUid(ctx, req.(*Uid))
	}
	return interceptor(ctx, in, info, handler)
}

func _MblogUser_GetByNicknameAndPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MblogUserServer).GetByNicknameAndPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userGrpc.MblogUser/GetByNicknameAndPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MblogUserServer).GetByNicknameAndPassword(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _MblogUser_GetMultiByUids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uids)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MblogUserServer).GetMultiByUids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userGrpc.MblogUser/GetMultiByUids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MblogUserServer).GetMultiByUids(ctx, req.(*Uids))
	}
	return interceptor(ctx, in, info, handler)
}

var _MblogUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userGrpc.MblogUser",
	HandlerType: (*MblogUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MblogUser_Create_Handler,
		},
		{
			MethodName: "GetByUid",
			Handler:    _MblogUser_GetByUid_Handler,
		},
		{
			MethodName: "GetByNicknameAndPassword",
			Handler:    _MblogUser_GetByNicknameAndPassword_Handler,
		},
		{
			MethodName: "GetMultiByUids",
			Handler:    _MblogUser_GetMultiByUids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
