// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userGrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  int64                `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	NickName             string               `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Telephone            string               `protobuf:"bytes,5,opt,name=Telephone,proto3" json:"Telephone,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	ProfileImages        string               `protobuf:"bytes,7,opt,name=ProfileImages,proto3" json:"ProfileImages,omitempty"`
	FollowsCount         int64                `protobuf:"varint,8,opt,name=FollowsCount,proto3" json:"FollowsCount,omitempty"`
	FriendsCount         int64                `protobuf:"varint,9,opt,name=FriendsCount,proto3" json:"FriendsCount,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetProfileImages() string {
	if m != nil {
		return m.ProfileImages
	}
	return ""
}

func (m *User) GetFollowsCount() int64 {
	if m != nil {
		return m.FollowsCount
	}
	return 0
}

func (m *User) GetFriendsCount() int64 {
	if m != nil {
		return m.FriendsCount
	}
	return 0
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type MultiUsers struct {
	UserInfo             []*User  `protobuf:"bytes,1,rep,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiUsers) Reset()         { *m = MultiUsers{} }
func (m *MultiUsers) String() string { return proto.CompactTextString(m) }
func (*MultiUsers) ProtoMessage()    {}
func (*MultiUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *MultiUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiUsers.Unmarshal(m, b)
}
func (m *MultiUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiUsers.Marshal(b, m, deterministic)
}
func (m *MultiUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiUsers.Merge(m, src)
}
func (m *MultiUsers) XXX_Size() int {
	return xxx_messageInfo_MultiUsers.Size(m)
}
func (m *MultiUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiUsers.DiscardUnknown(m)
}

var xxx_messageInfo_MultiUsers proto.InternalMessageInfo

func (m *MultiUsers) GetUserInfo() []*User {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type Uid struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uid) Reset()         { *m = Uid{} }
func (m *Uid) String() string { return proto.CompactTextString(m) }
func (*Uid) ProtoMessage()    {}
func (*Uid) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Uid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uid.Unmarshal(m, b)
}
func (m *Uid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uid.Marshal(b, m, deterministic)
}
func (m *Uid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uid.Merge(m, src)
}
func (m *Uid) XXX_Size() int {
	return xxx_messageInfo_Uid.Size(m)
}
func (m *Uid) XXX_DiscardUnknown() {
	xxx_messageInfo_Uid.DiscardUnknown(m)
}

var xxx_messageInfo_Uid proto.InternalMessageInfo

func (m *Uid) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "userGrpc.User")
	proto.RegisterType((*MultiUsers)(nil), "userGrpc.MultiUsers")
	proto.RegisterType((*Uid)(nil), "userGrpc.Uid")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x24, 0x6d, 0xdf, 0x74, 0xfa, 0xb6, 0xbc, 0x2c, 0x82, 0x4b, 0x10, 0x0c, 0xc1,
	0x43, 0x50, 0x48, 0xa1, 0x1e, 0x14, 0x8f, 0x16, 0x2d, 0x39, 0x58, 0x4a, 0x6c, 0x3f, 0x40, 0xda,
	0x4c, 0xeb, 0x62, 0x92, 0x0d, 0xbb, 0x89, 0xc5, 0xaf, 0xee, 0x49, 0x76, 0xd3, 0xf4, 0x8f, 0x17,
	0x6f, 0x33, 0xcf, 0xf3, 0x9b, 0x61, 0x98, 0x07, 0xa0, 0x92, 0x28, 0x82, 0x42, 0xf0, 0x92, 0x13,
	0x5b, 0xd5, 0x13, 0x51, 0xac, 0x9c, 0xcb, 0x0d, 0xe7, 0x9b, 0x14, 0x87, 0x5a, 0x5f, 0x56, 0xeb,
	0x61, 0xc9, 0x32, 0x94, 0x65, 0x9c, 0x15, 0x35, 0xea, 0x7d, 0x99, 0xd0, 0x5a, 0x48, 0x14, 0x64,
	0x00, 0x66, 0x98, 0x50, 0xc3, 0x35, 0xfc, 0x76, 0x64, 0x86, 0x09, 0xf9, 0x0f, 0xd6, 0x82, 0x25,
	0xd4, 0x74, 0x0d, 0xdf, 0x8a, 0x54, 0x49, 0x1c, 0xb0, 0xa7, 0x6c, 0xf5, 0x3e, 0x8d, 0x33, 0xa4,
	0x96, 0x6b, 0xf8, 0xdd, 0x68, 0xdf, 0x2b, 0x6f, 0x16, 0x4b, 0xb9, 0xe5, 0x22, 0xa1, 0xad, 0xda,
	0x6b, 0x7a, 0x72, 0x01, 0xdd, 0x39, 0xa6, 0x58, 0xbc, 0xf1, 0x1c, 0x69, 0x5b, 0x9b, 0x07, 0x81,
	0x9c, 0x41, 0xfb, 0x29, 0x8b, 0x59, 0x4a, 0x3b, 0xda, 0xa9, 0x1b, 0x72, 0x05, 0xfd, 0x99, 0xe0,
	0x6b, 0x96, 0x62, 0x98, 0xc5, 0x1b, 0x94, 0xf4, 0xaf, 0x76, 0x4f, 0x45, 0xe2, 0xc1, 0xbf, 0x67,
	0x9e, 0xa6, 0x7c, 0x2b, 0xc7, 0xbc, 0xca, 0x4b, 0x6a, 0xeb, 0x63, 0x4f, 0x34, 0xcd, 0x08, 0x86,
	0x79, 0xb2, 0x63, 0xba, 0x3b, 0xe6, 0x48, 0x23, 0x0f, 0x00, 0x63, 0x81, 0x71, 0x89, 0x73, 0x96,
	0x21, 0x05, 0xd7, 0xf0, 0x7b, 0x23, 0x27, 0xa8, 0x5f, 0x17, 0x34, 0xaf, 0x0b, 0xe6, 0xcd, 0xeb,
	0xa2, 0x23, 0x5a, 0xcd, 0x2e, 0x8a, 0xa4, 0x99, 0xed, 0xfd, 0x3e, 0x7b, 0xa0, 0xbd, 0x7b, 0x80,
	0x97, 0x2a, 0x2d, 0x99, 0x0a, 0x40, 0x92, 0x6b, 0xd0, 0xb9, 0x85, 0xf9, 0x9a, 0x53, 0xc3, 0xb5,
	0xfc, 0xde, 0x68, 0x10, 0x34, 0x41, 0x06, 0x0a, 0x89, 0xf6, 0xbe, 0x77, 0xae, 0xd3, 0x69, 0x42,
	0x32, 0xf6, 0x21, 0x8d, 0xee, 0xc0, 0x56, 0xe8, 0x2b, 0x8a, 0x0f, 0x72, 0x03, 0xf6, 0x04, 0xcb,
	0xc7, 0x4f, 0x45, 0xf6, 0x8f, 0x56, 0xb1, 0xc4, 0xf9, 0xb1, 0xd9, 0xfb, 0xb3, 0xec, 0xe8, 0x5b,
	0x6f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x97, 0xc1, 0x6e, 0x48, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServClient is the client API for UserServ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServClient interface {
	GetByUid(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*User, error)
}

type userServClient struct {
	cc *grpc.ClientConn
}

func NewUserServClient(cc *grpc.ClientConn) UserServClient {
	return &userServClient{cc}
}

func (c *userServClient) GetByUid(ctx context.Context, in *Uid, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/userGrpc.UserServ/GetByUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServServer is the server API for UserServ service.
type UserServServer interface {
	GetByUid(context.Context, *Uid) (*User, error)
}

func RegisterUserServServer(s *grpc.Server, srv UserServServer) {
	s.RegisterService(&_UserServ_serviceDesc, srv)
}

func _UserServ_GetByUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Uid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServServer).GetByUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userGrpc.UserServ/GetByUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServServer).GetByUid(ctx, req.(*Uid))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userGrpc.UserServ",
	HandlerType: (*UserServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByUid",
			Handler:    _UserServ_GetByUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
