// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mblog.proto

package mblogProto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MblogInfo struct {
	Id                   int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Mid                  int64                `protobuf:"varint,2,opt,name=Mid,proto3" json:"Mid,omitempty"`
	Uid                  int64                `protobuf:"varint,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Content              string               `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	OriginMid            int64                `protobuf:"varint,5,opt,name=OriginMid,proto3" json:"OriginMid,omitempty"`
	OriginUid            int64                `protobuf:"varint,6,opt,name=OriginUid,proto3" json:"OriginUid,omitempty"`
	TransCnt             int32                `protobuf:"varint,7,opt,name=TransCnt,proto3" json:"TransCnt,omitempty"`
	LikesCnt             int32                `protobuf:"varint,8,opt,name=LikesCnt,proto3" json:"LikesCnt,omitempty"`
	CommentCnt           int32                `protobuf:"varint,9,opt,name=CommentCnt,proto3" json:"CommentCnt,omitempty"`
	Status               int32                `protobuf:"varint,10,opt,name=Status,proto3" json:"Status,omitempty"`
	ReadAble             int32                `protobuf:"varint,11,opt,name=ReadAble,proto3" json:"ReadAble,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,12,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,13,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MblogInfo) Reset()         { *m = MblogInfo{} }
func (m *MblogInfo) String() string { return proto.CompactTextString(m) }
func (*MblogInfo) ProtoMessage()    {}
func (*MblogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9582175b6b4a736, []int{0}
}

func (m *MblogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MblogInfo.Unmarshal(m, b)
}
func (m *MblogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MblogInfo.Marshal(b, m, deterministic)
}
func (m *MblogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MblogInfo.Merge(m, src)
}
func (m *MblogInfo) XXX_Size() int {
	return xxx_messageInfo_MblogInfo.Size(m)
}
func (m *MblogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MblogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MblogInfo proto.InternalMessageInfo

func (m *MblogInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MblogInfo) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *MblogInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MblogInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MblogInfo) GetOriginMid() int64 {
	if m != nil {
		return m.OriginMid
	}
	return 0
}

func (m *MblogInfo) GetOriginUid() int64 {
	if m != nil {
		return m.OriginUid
	}
	return 0
}

func (m *MblogInfo) GetTransCnt() int32 {
	if m != nil {
		return m.TransCnt
	}
	return 0
}

func (m *MblogInfo) GetLikesCnt() int32 {
	if m != nil {
		return m.LikesCnt
	}
	return 0
}

func (m *MblogInfo) GetCommentCnt() int32 {
	if m != nil {
		return m.CommentCnt
	}
	return 0
}

func (m *MblogInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MblogInfo) GetReadAble() int32 {
	if m != nil {
		return m.ReadAble
	}
	return 0
}

func (m *MblogInfo) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *MblogInfo) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type MultiMblogs struct {
	MblogInfo            []*MblogInfo `protobuf:"bytes,1,rep,name=mblogInfo,proto3" json:"mblogInfo,omitempty"`
	Cnt                  int64        `protobuf:"varint,2,opt,name=Cnt,proto3" json:"Cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MultiMblogs) Reset()         { *m = MultiMblogs{} }
func (m *MultiMblogs) String() string { return proto.CompactTextString(m) }
func (*MultiMblogs) ProtoMessage()    {}
func (*MultiMblogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9582175b6b4a736, []int{1}
}

func (m *MultiMblogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiMblogs.Unmarshal(m, b)
}
func (m *MultiMblogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiMblogs.Marshal(b, m, deterministic)
}
func (m *MultiMblogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiMblogs.Merge(m, src)
}
func (m *MultiMblogs) XXX_Size() int {
	return xxx_messageInfo_MultiMblogs.Size(m)
}
func (m *MultiMblogs) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiMblogs.DiscardUnknown(m)
}

var xxx_messageInfo_MultiMblogs proto.InternalMessageInfo

func (m *MultiMblogs) GetMblogInfo() []*MblogInfo {
	if m != nil {
		return m.MblogInfo
	}
	return nil
}

func (m *MultiMblogs) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

type UidReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	ReadAble             []int32  `protobuf:"varint,4,rep,packed,name=readAble,proto3" json:"readAble,omitempty"`
	StartTime            int64    `protobuf:"varint,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64    `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidReq) Reset()         { *m = UidReq{} }
func (m *UidReq) String() string { return proto.CompactTextString(m) }
func (*UidReq) ProtoMessage()    {}
func (*UidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9582175b6b4a736, []int{2}
}

func (m *UidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidReq.Unmarshal(m, b)
}
func (m *UidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidReq.Marshal(b, m, deterministic)
}
func (m *UidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidReq.Merge(m, src)
}
func (m *UidReq) XXX_Size() int {
	return xxx_messageInfo_UidReq.Size(m)
}
func (m *UidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UidReq.DiscardUnknown(m)
}

var xxx_messageInfo_UidReq proto.InternalMessageInfo

func (m *UidReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UidReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UidReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *UidReq) GetReadAble() []int32 {
	if m != nil {
		return m.ReadAble
	}
	return nil
}

func (m *UidReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *UidReq) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type MidsReq struct {
	Mid                  []int64  `protobuf:"varint,1,rep,packed,name=Mid,proto3" json:"Mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MidsReq) Reset()         { *m = MidsReq{} }
func (m *MidsReq) String() string { return proto.CompactTextString(m) }
func (*MidsReq) ProtoMessage()    {}
func (*MidsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9582175b6b4a736, []int{3}
}

func (m *MidsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MidsReq.Unmarshal(m, b)
}
func (m *MidsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MidsReq.Marshal(b, m, deterministic)
}
func (m *MidsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MidsReq.Merge(m, src)
}
func (m *MidsReq) XXX_Size() int {
	return xxx_messageInfo_MidsReq.Size(m)
}
func (m *MidsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MidsReq.DiscardUnknown(m)
}

var xxx_messageInfo_MidsReq proto.InternalMessageInfo

func (m *MidsReq) GetMid() []int64 {
	if m != nil {
		return m.Mid
	}
	return nil
}

type MidReq struct {
	Mid                  int64    `protobuf:"varint,1,opt,name=Mid,proto3" json:"Mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MidReq) Reset()         { *m = MidReq{} }
func (m *MidReq) String() string { return proto.CompactTextString(m) }
func (*MidReq) ProtoMessage()    {}
func (*MidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9582175b6b4a736, []int{4}
}

func (m *MidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MidReq.Unmarshal(m, b)
}
func (m *MidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MidReq.Marshal(b, m, deterministic)
}
func (m *MidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MidReq.Merge(m, src)
}
func (m *MidReq) XXX_Size() int {
	return xxx_messageInfo_MidReq.Size(m)
}
func (m *MidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MidReq.DiscardUnknown(m)
}

var xxx_messageInfo_MidReq proto.InternalMessageInfo

func (m *MidReq) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func init() {
	proto.RegisterType((*MblogInfo)(nil), "mblogProto.MblogInfo")
	proto.RegisterType((*MultiMblogs)(nil), "mblogProto.MultiMblogs")
	proto.RegisterType((*UidReq)(nil), "mblogProto.UidReq")
	proto.RegisterType((*MidsReq)(nil), "mblogProto.MidsReq")
	proto.RegisterType((*MidReq)(nil), "mblogProto.MidReq")
}

func init() { proto.RegisterFile("mblog.proto", fileDescriptor_a9582175b6b4a736) }

var fileDescriptor_a9582175b6b4a736 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xe3, 0xc4, 0xa9, 0xc7, 0x50, 0xa1, 0x45, 0xc0, 0xca, 0x20, 0xb0, 0x7c, 0xf2, 0xc9,
	0x95, 0xd2, 0x0b, 0xe2, 0x02, 0xd4, 0x42, 0x28, 0x12, 0x86, 0xca, 0x49, 0x7e, 0x80, 0xa3, 0xdd,
	0x5a, 0x2b, 0xfc, 0x11, 0xec, 0xcd, 0xa1, 0xfc, 0x13, 0x2e, 0xfc, 0x1a, 0x7e, 0x18, 0x9a, 0xb1,
	0xd7, 0x4e, 0xa5, 0x0a, 0x4e, 0xbb, 0x6f, 0xde, 0x9b, 0xd1, 0xec, 0x7b, 0x0b, 0x5e, 0xb5, 0x2f,
	0x9b, 0x22, 0x3e, 0xb4, 0x8d, 0x6e, 0x18, 0x10, 0xb8, 0xc1, 0xbb, 0xff, 0xa6, 0x68, 0x9a, 0xa2,
	0x94, 0x97, 0xc4, 0xec, 0x8f, 0xb7, 0x97, 0x5a, 0x55, 0xb2, 0xd3, 0x79, 0x75, 0xe8, 0xc5, 0xe1,
	0x2f, 0x1b, 0xdc, 0x14, 0xf5, 0xeb, 0xfa, 0xb6, 0x61, 0x17, 0x30, 0x5b, 0x0b, 0x6e, 0x05, 0x56,
	0xb4, 0xc8, 0x66, 0x6b, 0xc1, 0x9e, 0x80, 0x9d, 0x2a, 0xc1, 0x67, 0x81, 0x15, 0xd9, 0x19, 0x5e,
	0xb1, 0xb2, 0x53, 0x82, 0xdb, 0x7d, 0x65, 0xa7, 0x04, 0xe3, 0xb0, 0x4c, 0x9a, 0x5a, 0xcb, 0x5a,
	0xf3, 0x79, 0x60, 0x45, 0x6e, 0x66, 0x20, 0x7b, 0x05, 0xee, 0xb7, 0x56, 0x15, 0xaa, 0xc6, 0x19,
	0x0b, 0xea, 0x98, 0x0a, 0x13, 0x8b, 0xf3, 0x9c, 0x53, 0x16, 0xa7, 0xfa, 0x70, 0xbe, 0x6d, 0xf3,
	0xba, 0x4b, 0x6a, 0xcd, 0x97, 0xb4, 0xcf, 0x88, 0x91, 0xfb, 0xa2, 0xbe, 0x4b, 0xe2, 0xce, 0x7b,
	0xce, 0x60, 0xf6, 0x1a, 0x20, 0x69, 0xaa, 0x4a, 0xd6, 0x1a, 0x59, 0x97, 0xd8, 0x93, 0x0a, 0x7b,
	0x0e, 0xce, 0x46, 0xe7, 0xfa, 0xd8, 0x71, 0x20, 0x6e, 0x40, 0x38, 0x33, 0x93, 0xb9, 0xf8, 0xb8,
	0x2f, 0x25, 0xf7, 0xfa, 0x99, 0x06, 0xb3, 0x77, 0x00, 0x49, 0x2b, 0x73, 0x2d, 0xb7, 0xaa, 0x92,
	0xfc, 0x51, 0x60, 0x45, 0xde, 0xca, 0x8f, 0x7b, 0x67, 0x63, 0xe3, 0x6c, 0xbc, 0x35, 0xce, 0x66,
	0x27, 0x6a, 0xec, 0xdd, 0x1d, 0x84, 0xe9, 0x7d, 0xfc, 0xff, 0xde, 0x49, 0x1d, 0x6e, 0xc1, 0x4b,
	0x8f, 0xa5, 0x56, 0x94, 0x4f, 0xc7, 0xae, 0xc0, 0xad, 0x4c, 0x52, 0xdc, 0x0a, 0xec, 0xc8, 0x5b,
	0x3d, 0x8b, 0xa7, 0xac, 0xe3, 0x31, 0xc6, 0x6c, 0xd2, 0x61, 0x5e, 0x68, 0xc4, 0x90, 0x60, 0x52,
	0xeb, 0xf0, 0xb7, 0x05, 0xce, 0x4e, 0x89, 0x4c, 0xfe, 0x30, 0x61, 0x5a, 0x53, 0x98, 0x0c, 0xe6,
	0x37, 0x79, 0x21, 0x49, 0xbf, 0xc8, 0xe8, 0x8e, 0xd6, 0xe0, 0xb9, 0x51, 0x3f, 0x25, 0xe5, 0xbe,
	0xc8, 0x46, 0x8c, 0x5c, 0x6b, 0x6c, 0x9b, 0x07, 0x36, 0x72, 0x06, 0x63, 0xc0, 0x1b, 0x9d, 0xb7,
	0x9a, 0x5e, 0x3e, 0xc4, 0x3f, 0x16, 0xf0, 0xdb, 0x7c, 0xaa, 0x05, 0x71, 0x7d, 0xf8, 0x06, 0x86,
	0x2f, 0x61, 0x99, 0x2a, 0xd1, 0x0d, 0x0b, 0xa6, 0xb4, 0xa0, 0x3d, 0xfc, 0xbf, 0xd0, 0x07, 0x27,
	0x1d, 0x97, 0x4f, 0xa7, 0xe5, 0x53, 0x25, 0x56, 0x7f, 0x2c, 0x58, 0x90, 0x09, 0xec, 0x2d, 0x38,
	0x7d, 0x06, 0xec, 0x61, 0x87, 0xfc, 0x87, 0xcb, 0xe1, 0x19, 0x7b, 0x0f, 0x17, 0x9f, 0xa5, 0xfe,
	0xda, 0xb4, 0x55, 0x5e, 0x5e, 0xdf, 0x91, 0x25, 0xa7, 0xd2, 0xde, 0x38, 0xff, 0xc5, 0xbd, 0xf6,
	0x29, 0xa3, 0xf0, 0x8c, 0x7d, 0xa0, 0x01, 0x54, 0xbb, 0xbe, 0xc3, 0x77, 0xb0, 0xa7, 0xf7, 0xc4,
	0xfd, 0xcb, 0xfe, 0x31, 0x61, 0xef, 0xd0, 0xb7, 0xb8, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x9e,
	0x72, 0x53, 0x70, 0xd5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MblogClient is the client API for Mblog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MblogClient interface {
	Create(ctx context.Context, in *MblogInfo, opts ...grpc.CallOption) (*MblogInfo, error)
	GetNormalByUid(ctx context.Context, in *UidReq, opts ...grpc.CallOption) (*MultiMblogs, error)
	GetMultiByMids(ctx context.Context, in *MidsReq, opts ...grpc.CallOption) (*MultiMblogs, error)
}

type mblogClient struct {
	cc *grpc.ClientConn
}

func NewMblogClient(cc *grpc.ClientConn) MblogClient {
	return &mblogClient{cc}
}

func (c *mblogClient) Create(ctx context.Context, in *MblogInfo, opts ...grpc.CallOption) (*MblogInfo, error) {
	out := new(MblogInfo)
	err := c.cc.Invoke(ctx, "/mblogProto.Mblog/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mblogClient) GetNormalByUid(ctx context.Context, in *UidReq, opts ...grpc.CallOption) (*MultiMblogs, error) {
	out := new(MultiMblogs)
	err := c.cc.Invoke(ctx, "/mblogProto.Mblog/GetNormalByUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mblogClient) GetMultiByMids(ctx context.Context, in *MidsReq, opts ...grpc.CallOption) (*MultiMblogs, error) {
	out := new(MultiMblogs)
	err := c.cc.Invoke(ctx, "/mblogProto.Mblog/GetMultiByMids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MblogServer is the server API for Mblog service.
type MblogServer interface {
	Create(context.Context, *MblogInfo) (*MblogInfo, error)
	GetNormalByUid(context.Context, *UidReq) (*MultiMblogs, error)
	GetMultiByMids(context.Context, *MidsReq) (*MultiMblogs, error)
}

func RegisterMblogServer(s *grpc.Server, srv MblogServer) {
	s.RegisterService(&_Mblog_serviceDesc, srv)
}

func _Mblog_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MblogInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MblogServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mblogProto.Mblog/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MblogServer).Create(ctx, req.(*MblogInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mblog_GetNormalByUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MblogServer).GetNormalByUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mblogProto.Mblog/GetNormalByUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MblogServer).GetNormalByUid(ctx, req.(*UidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mblog_GetMultiByMids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MidsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MblogServer).GetMultiByMids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mblogProto.Mblog/GetMultiByMids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MblogServer).GetMultiByMids(ctx, req.(*MidsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mblog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mblogProto.Mblog",
	HandlerType: (*MblogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Mblog_Create_Handler,
		},
		{
			MethodName: "GetNormalByUid",
			Handler:    _Mblog_GetNormalByUid_Handler,
		},
		{
			MethodName: "GetMultiByMids",
			Handler:    _Mblog_GetMultiByMids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mblog.proto",
}
